name: app_map
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.1.0
  background_locator: ^1.6.4
  build_runner: ^2.0.6
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  expandable_bottom_sheet: ^1.1.0
  flutter_polyline_points: ^1.0.0
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
  flutter_vibrate: ^1.1.0
  geocoding: ^2.0.0
  geolocator: ^7.2.0+1
  google_maps_flutter: ^2.0.6
  hive: ^2.0.4
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  jiffy: ^4.1.0
  kiwi: ^3.0.0
  kiwi_generator: ^3.0.0
  location: ^4.3.0
  location_permissions: ^4.0.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.2
  provider: ^5.0.0
  sembast: ^3.1.0+2
  shared_preferences: ^2.0.6
  slidable_button: ^1.0.1+2
  sqflite: ^2.0.0+3
  workmanager: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
